name: Trigger Antora Documentation Build

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch event
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.GH_PAT }}" \
          https://api.github.com/repos/FelixGeisler/FLOWAntora/dispatches \
          -d '{"event_type": "build-antora"}'
